# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_helium.ui'
#
# Created: Tue May 20 09:43:57 2014
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(626, 397)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(225, 225))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.labelFlow = QtGui.QLabel(self.groupBox)
        self.labelFlow.setGeometry(QtCore.QRect(10, 40, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelFlow.setFont(font)
        self.labelFlow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFlow.setObjectName(_fromUtf8("labelFlow"))
        self.labelVolume = QtGui.QLabel(self.groupBox)
        self.labelVolume.setGeometry(QtCore.QRect(20, 0, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelVolume.setFont(font)
        self.labelVolume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelVolume.setObjectName(_fromUtf8("labelVolume"))
        self.labelLevelMeter = QtGui.QLabel(self.groupBox)
        self.labelLevelMeter.setGeometry(QtCore.QRect(10, 80, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelLevelMeter.setFont(font)
        self.labelLevelMeter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLevelMeter.setObjectName(_fromUtf8("labelLevelMeter"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 229, 211, 101))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(80, 70, 16, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.editRefresh = QtGui.QLineEdit(self.groupBox_2)
        self.editRefresh.setGeometry(QtCore.QRect(20, 70, 51, 20))
        self.editRefresh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.editRefresh.setObjectName(_fromUtf8("editRefresh"))
        self.editSetVolume = QtGui.QLineEdit(self.groupBox_2)
        self.editSetVolume.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.editSetVolume.setObjectName(_fromUtf8("editSetVolume"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(120, 50, 71, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(180, 70, 16, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.editRange = QtGui.QLineEdit(self.groupBox_2)
        self.editRange.setGeometry(QtCore.QRect(120, 70, 51, 20))
        self.editRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.editRange.setObjectName(_fromUtf8("editRange"))
        self.btnSetVolume = QtGui.QPushButton(self.groupBox_2)
        self.btnSetVolume.setGeometry(QtCore.QRect(110, 20, 81, 23))
        self.btnSetVolume.setObjectName(_fromUtf8("btnSetVolume"))
        self.labelLevelMeter_2 = QtGui.QLabel(self.groupBox)
        self.labelLevelMeter_2.setGeometry(QtCore.QRect(10, 120, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelLevelMeter_2.setFont(font)
        self.labelLevelMeter_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLevelMeter_2.setObjectName(_fromUtf8("labelLevelMeter_2"))
        self.btnHe = QtGui.QToolButton(self.groupBox)
        self.btnHe.setGeometry(QtCore.QRect(30, 200, 25, 19))
        self.btnHe.setObjectName(_fromUtf8("btnHe"))
        self.btnN2 = QtGui.QToolButton(self.groupBox)
        self.btnN2.setGeometry(QtCore.QRect(60, 200, 25, 19))
        self.btnN2.setObjectName(_fromUtf8("btnN2"))
        self.btnZzz = QtGui.QToolButton(self.groupBox)
        self.btnZzz.setGeometry(QtCore.QRect(90, 200, 25, 19))
        self.btnZzz.setObjectName(_fromUtf8("btnZzz"))
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.curvewidget = CurveWidget(self.centralwidget)
        self.curvewidget.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget.setObjectName(_fromUtf8("curvewidget"))
        self.verticalLayout.addWidget(self.curvewidget)
        self.curvewidget_2 = CurveWidget(self.centralwidget)
        self.curvewidget_2.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_2.setObjectName(_fromUtf8("curvewidget_2"))
        self.verticalLayout.addWidget(self.curvewidget_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Helium Monitor by David Weber", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFlow.setText(QtGui.QApplication.translate("MainWindow", "100 L/h", None, QtGui.QApplication.UnicodeUTF8))
        self.labelVolume.setText(QtGui.QApplication.translate("MainWindow", "7864320 L", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevelMeter.setText(QtGui.QApplication.translate("MainWindow", "100 mm", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.editRefresh.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Interpolate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.editRange.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetVolume.setText(QtGui.QApplication.translate("MainWindow", "Set Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevelMeter_2.setText(QtGui.QApplication.translate("MainWindow", "100 mm", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHe.setText(QtGui.QApplication.translate("MainWindow", "He", None, QtGui.QApplication.UnicodeUTF8))
        self.btnN2.setText(QtGui.QApplication.translate("MainWindow", "N2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZzz.setText(QtGui.QApplication.translate("MainWindow", "Zzz", None, QtGui.QApplication.UnicodeUTF8))

from guiqwt.plot import CurveWidget
